### ISSUE TITLE
GIN Land Cover Data Empty Geometry Column 

### ISSUE THREAD

**Issue by dasalm20** [SSA-Statistical-Team-Projects/S2S-Imputation-WAEMU#13]
The column   <.geo > appears to be empty. I did sum(gin_data$.geo) and I got NA. I tried pulling the data with the NTL file and I still got an empty geometry column. I am not sure what the issue is.

**Comment by ifeanyi588** [comment]
As I mentioned, lets use the "ID" variable within the dataset to deal with this
